name: Pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install protoc
        run: |
          wget -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip
          unzip /tmp/protoc.zip -d /tmp/protoc3
          sudo mv /tmp/protoc3/bin/* /usr/local/bin/
          sudo mv /tmp/protoc3/include/* /usr/local/include/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
          npm run test:generate
          npm run test
